version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: evaluacion-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: evaluacion-db
    volumes:
      - mongodb_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: evaluacion-backend-test
    container_name: evaluacion-backend-test
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/evaluacion-db
      PORT: 3000
    depends_on:
      - mongodb

volumes:
  mongodb_data:
